# Generated by Django 4.0.5 on 2022-06-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_value', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.authuser')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.fooditems')),
            ],
            options={
                'db_table': 'ratings',
                'managed': True,
                'unique_together': {('user', 'food')},
            },
        ),
    ]
