# Generated by Django 4.0.5 on 2022-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='food_name',
            field=models.CharField(max_length=30),
        ),
    ]
