# Generated by Django 4.0.5 on 2022-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fooditems_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='avg_rating',
            field=models.IntegerField(null=True),
        ),
    ]
