# Generated by Django 4.0.5 on 2022-06-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fooditems_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodavailability',
            name='availability',
        ),
    ]
