# Generated by Django 4.0.5 on 2022-06-30 03:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_foodavailability_availability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='foodavailability',
            name='food_availability_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodavailability',
            name='avail_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='foodavailability',
            name='avail_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, size=3),
        ),
        migrations.AlterField(
            model_name='foodavailability',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.fooditems'),
        ),
    ]
